version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: moto-ext
    versions:
    - 1.3.15.49
    - 1.3.15.50
    - 1.3.15.51
    - 1.3.15.52
    - 2.0.1
    - 2.0.2
    - 2.0.3
    - 2.0.3.2
    - 2.0.3.3
    - 2.0.3.4
    - 2.0.3.5
    - 2.0.3.7
    - 2.0.3.8
